{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cosmos-node.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cosmos-node.labels" . | nindent 4 }}
  {{- with (include "cosmos-node.commonAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
  # Allow reading ConfigMaps for configuration updates
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  # Allow reading secrets if needed for key management
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  # Allow creating events for logging
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  {{- with .Values.rbac.rules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cosmos-node.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cosmos-node.labels" . | nindent 4 }}
  {{- with (include "cosmos-node.commonAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cosmos-node.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "cosmos-node.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
