net: mainnet   # mainnet or testnet

replicaCount: 1

snapshot:
  enabled: true
  url: "$(curl -s https://polkachu.com/api/v2/chain_snapshots/cosmos/mainnet | jq -r .snapshot.url)"

image:
  repository: ghcr.io/cosmos/gaia
  pullPolicy: IfNotPresent
  # -- Overrides the image tag
  # @default -- Chart.appVersion
  tag: ""

flags: 
# - --p2p.persistent_peers=648742a99b2714a442506bd5dbefe74c40346fbd@18.225.13.106:26656,...


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  annotations: {}
  port:
    p2p: 26656
    rpc: 26657
    grpc: 9090

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
          servicePort: rpc
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistence:
  enabled: true
  size: "250Gi"
  accessMode: ReadWriteOnce
  storageClass: "-" # set to "-" to use default storageClass
pvc:
  annotations: {}

resources:
  requests:
    cpu: 4
    memory: 16Gi
  limits:
    memory: 48Gi

nodeSelector: {}

tolerations: []

affinity: {}