apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cosmoshub.fullname" . }}
  labels:
    {{- include "cosmoshub.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.pvc.annotations | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "100Gi" }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}