apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cosmoshub.fullname" . }}
  labels:
    {{- include "cosmoshub.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"