apiVersion: v1
kind: Service
metadata:
  name: {{ include "cosmoshub.fullname" . }}
  labels:
    {{- include "cosmoshub.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.p2p }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: {{ .Values.service.port.rpc }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.port.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "cosmoshub.selectorLabels" . | nindent 4 }}