{{- $values := $.Values.fullMode }}
{{- $componentName := "op-node" }}
{{- $componentLabel := include "firehose-ethereum.componentLabelFor" $componentName }}
{{- if and (eq .Values.mode "full") $values.components.opNode.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-firehose-{{ $componentName }}-svc
  labels:
    {{- include "firehose-ethereum.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "firehose-ethereum.selectorLabels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
  ports:
    - name: http-rpc
      port: 9545
      targetPort: http-rpc
      protocol: TCP
    - name: http-metrics
      port: 7300
      targetPort: http-metrics
      protocol: TCP
{{- end }}

