# values.yaml
replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/vincenttaglia/indexer-tools
  tag: "v3.4.0-beta5"
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

env:
  variables:
    - name: AGENT_SERVICE
      value: "http://indexer-graph-network-indexer-agent:8000"
    - name: GRAPH_API_KEY
      value: "<api-key>" # Will override the [api-key] default value below
    - name: DEFAULT_ACCOUNTS
      value: '[ { "address": "0x.............", "name": "my-indexer-name", "active": true, "chain": "arbitrum-one", "agentConnect": true, "agentEndpoint": "/agent", "poiQuery": false, "poiQueryEndpoint": "" } ]'
    - name: DEFAULT_QOS_SUBGRAPH
      value: "https://gateway.thegraph.com/api/[api-key]/subgraphs/id/Dtr9rETvwokot4BSXaD5tECanXfqfJKcvHuaaEgPDD2D"
    - name: DEFAULT_SUBGRAPH_MAINNET
      value: "https://gateway.thegraph.com/api/[api-key]/subgraphs/id/9Co7EQe5PgW3ugCUJrJgRv4u9zdEuDJf8NvMWftNsBH8"
    - name: DEFAULT_SUBGRAPH_ARBITRUM 
      value: "https://gateway.thegraph.com/api/[api-key]/subgraphs/id/DZz4kDTdmzWLWsV373w2bSmoar3umKKH9y82SUKr5qmp"
    - name: DEFAULT_SUBGRAPH_SEPOLIA
      value: "https://gateway.thegraph.com/api/[api-key]/subgraphs/id/8pVKDwHniAz87CHEQsiz2wgFXGZXrbMDkrxgauVVfMJC"
    - name: DEFAULT_SUBGRAPH_ARBITRUM_SEPOLIA
      value: "https://gateway.thegraph.com/api/[api-key]/subgraphs/id/3xQHhMudr1oh69ut36G2mbzpYmYxwqCeU6wwqyCDCnqV"
    - name: DEFAULT_RPC_MAINNET
      value: "https://eth-mainnet.g.alchemy.com/v2/iwAYPKEO-K7EaRzaIoHUsIoCbiMfir_Y"
    - name: DEFAULT_RPC_ARBITRUM
      value: "https://arb-mainnet.g.alchemy.com/v2/er8LBcXpoFwlV8xJee-WXFbFG_M8L4JK"

podAnnotations: {}
podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

healthCheck:
  livenessProbe:
    tcpSocket:
      port: 3000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    tcpSocket:
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

nodeSelector: {}
tolerations: []
affinity: {}
