{{- $componentName := "substreams-sink-noop" }}

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "substreams-sink-noop.serviceAccountName" . }}
  labels:
    {{- include "substreams-sink-noop.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $componentName }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
