{{- $values := $.Values.substreams_sink_noop }}
{{- $componentName := "substreams-sink-noop" }}
{{- $componentLabel := include "substreams_sink_noop.componentLabelFor" $componentName }}

{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "substreams_sink_noop.fullname" . }}
  labels:
    {{- include "substreams_sink_noop.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "substreams_sink_noop.selectorLabels" . | nindent 6 }}
      {{- $componentLabel | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      {{- with .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
{{- end }}
