name: Deploy New Helm Chart to gh-pages

on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch
    paths:
      - "**/Chart.yaml"  # Trigger only when a Chart.yaml file is added

jobs:
  deploy-chart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure full commit history is available

    - name: Install Helm
      run: |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Identify Newly Added Charts
      id: find-new-charts
      run: |
        # Find newly added Chart.yaml files
        NEW_CHARTS=$(git diff --name-status HEAD^ HEAD | grep "^A" | grep "Chart.yaml" | awk '{print $2}' | xargs -n1 dirname)
        if [[ -z "$NEW_CHARTS" ]]; then
          echo "No new charts detected."
          exit 0
        fi
        echo "::set-output name=new_charts::$NEW_CHARTS"
      shell: bash

    - name: Debug New Charts
      if: ${{ steps.find-new-charts.outputs.new_charts != '' }}
      run: echo "New Charts: ${{ steps.find-new-charts.outputs.new_charts }}"

    - name: Package New Helm Charts
      if: ${{ steps.find-new-charts.outputs.new_charts != '' }}
      run: |
        mkdir -p packaged-charts
        for chart in ${{ steps.find-new-charts.outputs.new_charts }}; do
          helm package $chart --destination packaged-charts
        done

    - name: Checkout gh-pages Branch
      if: ${{ steps.find-new-charts.outputs.new_charts != '' }}
      uses: actions/checkout@v3
      with:
        ref: gh-pages  # Check out the gh-pages branch

    - name: Copy Packaged Charts
      if: ${{ steps.find-new-charts.outputs.new_charts != '' }}
      run: |
        mkdir -p charts
        mv ../packaged-charts/*.tgz charts/

    - name: Update Helm Repo Index
      if: ${{ steps.find-new-charts.outputs.new_charts != '' }}
      run: |
        helm repo index charts --url https://nodeify-eth.github.io/helm-charts/charts/

    - name: Commit and Push Changes
      if: ${{ steps.find-new-charts.outputs.new_charts != '' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add charts
        git commit -m "Add new Helm chart(s) and update index"
        git push